# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    container:
      image: ubuntu:latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt -y update
        apt -y install openssl
        apt -y install --reinstall python3.10 python3-pip python3.10-venv
        python3 -m venv .venv
        . .venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements-dev.txt
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        . .venv/bin/activate
        env LOG_LVL=DEBUG PYTHONPATH=$PYTHONPATH:src/ pytest

  test-archlinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pacman --noconfirm -Syu
        pacman --noconfirm -S python-pip
        python -m venv .venv
        . .venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements-dev.txt
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        . .venv/bin/activate
        env LOG_LVL=DEBUG PYTHONPATH=$PYTHONPATH:src/ pytest

  test-fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        dnf -y update
        dnf -y install openssl
        dnf -y reinstall python3.10 python3-pip python3.10-venv
        python3 -m venv .venv
        . .venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements-dev.txt
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        . .venv/bin/activate
        env LOG_LVL=DEBUG PYTHONPATH=$PYTHONPATH:src/ pytest
